#DRY principle
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mechanical-management-system-test?useSSL=false&serverTimezone=CET&useLegacyDatetimeCode=false
    username: root
    password: admin
  jpa:
    hibernate:
#      ddl-auto: create
#          ddl-auto: update
            ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:test-data.sql
      mode: always